# .streamlit/secrets.toml
# -------------------------
# NEVER commit this file to GitHub.
# It is already listed in .gitignore so Git will automatically ignore it.

DATABASE_URL = "postgresql://neondb_owner:npg_96CcwnDqfOWA@ep-snowy-cell-alm0evzs-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
SECRET_KEY   = "this is my ai powered health risk and monitoring app"